<a href="https://colab.research.google.com/github/nikamprachi750-cell/dataset_special_task/blob/main/Special_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files                          #uploaded csv file
import pandas as pd

uploaded = files.upload()

df = pd.read_csv("heart[1].csv")  # Replace with your actual file name

print(df.head())

Saving heart[1].csv to heart[1] (1).csv
   Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172
1   49   F           NAP        160          180          0     Normal    156
2   37   M           ATA        130          283          0         ST     98
3   48   F           ASY        138          214          0     Normal    108
4   54   M           NAP        150          195          0     Normal    122

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease
0              N      0.0       Up             0
1              N      1.0     Flat             1
2              N      0.0       Up             0
3              Y      1.5     Flat             1
4              N      0.0       Up             0

In [3]:
df                                                    #Prints whole dataset

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [4]:
df.tail()                                 #displays last 5 rows of dataframe

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [5]:
df.shape                                #Returns rows and columns as tuple

(918, 12)

In [6]:
df.info()                                 #prints column name,datatypes and non null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [7]:
df.columns                            #prints all column names

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [8]:
df.dtypes                                   #prints the datatype of each column

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [9]:
df.describe()                             #gives summary statistics for numeric columns

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [10]:
df.isnull().sum()                       #counts missing values per column

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [12]:
df.nunique()                                  #Counts unique values per column

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [14]:
df['Cholesterol']                             #Prints the single column

0      289
1      180
2      283
3      214
4      195
      ...
913    264
914    193
915    131
916    236
917    175
Name: Cholesterol, Length: 918, dtype: int64

In [16]:
df.loc[0,'ChestPainType']                           #selects rows/columns by labels

'ATA'

In [17]:
df.iloc[0:5,0:3]

   Age Sex ChestPainType
0   40   M           ATA
1   49   F           NAP
2   37   M           ATA
3   48   F           ASY
4   54   M           NAP

In [18]:
df.at[0,'ChestPainType']                          #fast access to a single value by label

'ATA'

In [20]:
df.sort_values('Age')                                 #sort rows by one or more columns

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
208,28,M,ATA,130,132,0,LVH,185,N,0.0,Up,0
829,29,M,ATA,130,204,0,LVH,202,N,0.0,Up,0
170,29,M,ATA,120,243,0,Normal,160,N,0.0,Up,0
219,29,M,ATA,140,263,0,Normal,170,N,0.0,Up,0
215,30,F,TA,170,237,0,ST,170,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
556,75,M,ASY,160,310,1,Normal,112,Y,2.0,Down,0
688,76,F,NAP,140,197,0,ST,116,N,1.1,Flat,0
541,76,M,NAP,104,113,0,LVH,120,N,3.5,Down,1
814,77,M,ASY,125,304,0,LVH,162,Y,0.0,Up,1
447,77,M,ASY,124,171,0,ST,110,Y,2.0,Up,1

In [22]:
df.groupby('Cholesterol')['MaxHR'].sum()        #Groups rows by a column for aggregation

Cholesterol
0      20982
85       140
100      258
110      109
113      120
       ...
491      135
518      130
529      130
564      160
603      125
Name: MaxHR, Length: 222, dtype: int64

In [23]:
df['RestingECG'].value_counts()                       #Counts Occurence of each unique value

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [24]:
df['Cholesterol'].mean()                        #calculates average values of a column

np.float64(198.7995642701525)

In [25]:
df['Cholesterol'].median()                        #calculates middle value of a column

223.0

In [30]:
df['RestingBP'].max()                           #Prints maximum value in column

200

In [31]:
df['RestingBP'].sum()                             #adds up all values in a column

np.int64(121540)

In [35]:
df['RestingBP'].fillna(0)                               #Replaes missing values with a given values

0      140
1      160
2      130
3      138
4      150
      ...
913    110
914    144
915    130
916    130
917    138
Name: RestingBP, Length: 918, dtype: int64

In [36]:
df.drop(columns=['Oldpeak'])                                #removes specified row or column

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,Up,0
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,Up,0